name: CI

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
#       - name: Black
#         uses: dciborow/pyaction@0.0.13
#         with:
#           black: true

#      - name: Bandit
#        uses: dciborow/pyaction@0.0.13
#        with:          
#          bandit: true

      - name: Pylint
        uses: dciborow/pyaction@0.0.13
        with:
          pylint: true
          
#      - name: Pyright
#        uses: dciborow/pyaction@0.0.13
#        with:          
#          pyright: true
          
      - name: Flake8
        uses: dciborow/pyaction@0.0.13
        with:          
          flake8: true
